// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package ent

type Jwt struct {
	Token string `json:"token"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}
