// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (c *Customer) Roles(ctx context.Context) (*Role, error) {
	result, err := c.Edges.RolesOrErr()
	if IsNotLoaded(err) {
		result, err = c.QueryRoles().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (r *Role) Customers(ctx context.Context) (result []*Customer, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = r.NamedCustomers(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = r.Edges.CustomersOrErr()
	}
	if IsNotLoaded(err) {
		result, err = r.QueryCustomers().All(ctx)
	}
	return result, err
}
